-- ============================================================
-- Velora · catalogue importé de Shopify
-- Source : jngiej-ax.myshopify.com · 2026-09-19T18:42:55.880Z
-- Généré par scripts/import-shopify-catalog.mjs — ne pas éditer à la main.
-- Idempotent : on upsert par slug / sku.
-- ============================================================

insert into products (slug, name, category, description, active) values ('hbelt-tg', 'H-Flex Belt™ – La ceinture sans boucle, confortable et ajustable', null, 'Découvrez la H-Flex Belt™, la ceinture révolutionnaire sans boucle qui vous offre confort et liberté totale. Fini la douleur au ventre, fini la boucle qui gêne : ◈ Confort absolu : fini la boucle qui rentre dans le ventre ◈ Ultra simple à utiliser : crochet + Velcro → prêt en 10 secondes ◈ Maintien parfait : votre pantalon reste en place toute la journée ◈ Unisexe & Taille Unique : s’adapte à toutes les morphologies', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'hbelt-tg-44834722119768', 'Default Title', null, 12500, 15500, 10, '[]'::jsonb from products where slug = 'hbelt-tg' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('tomi-dynasty-t106', 'TOMI Dynasty ™ T106 – La montre qui attire les regards', null, 'L''élégance ne fait pas de bruit. Elle se remarque. Vous n''avez pas besoin d''une montre à plusieurs centaines d''euros pour avoir de l''allure. La TOMI Dynasty™ T106 combine un design moderne, un cadran ajouré fascinant et une finition haut de gamme qui donnent immédiatement une impression de prestige. ◈ Design premium ◈ Style minimaliste et moderne ◈ Détails inspirés de l''horlogerie de luxe ◈ Mouvement Quartz de haute précision', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'tomi-dynasty-t106-44453399724120', 'Or Impérial', null, 16000, 18500, 10, '["/assets/shopify/72b3da1141.jpg"]'::jsonb from products where slug = 'tomi-dynasty-t106' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'tomi-dynasty-t106-44453399756888', 'Bleu Obsidienne', null, 16000, 18500, 10, '["/assets/shopify/8961973d53.jpg"]'::jsonb from products where slug = 'tomi-dynasty-t106' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('ceinture-aurion', 'AURION™ — La ceinture automatique en cuir véritable qui s''ajuste parfaitement à votre taille', null, 'Changez votre façon de porter une ceinture Une ceinture traditionnelle vous oblige à choisir entre plusieurs trous fixes. Trop serrée après un repas ? Trop lâche pendant la journée ? Ce problème appartient désormais au passé. ◈ Ajustement précis au millimètre près ◈ Design moderne et minimaliste ◈ Facile à mettre et à retirer ◈ Convient aux tenues professionnelles comme décontractées', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'ceinture-aurion-44439819092056', 'Noire', null, 12900, 15500, 10, '["/assets/shopify/95c276eb5e.jpg"]'::jsonb from products where slug = 'ceinture-aurion' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'ceinture-aurion-44439819124824', 'Marron', null, 12900, 15500, 10, '["/assets/shopify/9ed55e956b.jpg"]'::jsonb from products where slug = 'ceinture-aurion' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'ceinture-aurion-44439819157592', 'Marron Claire', null, 12900, 15500, 10, '["/assets/shopify/da5bc4c89d.png"]'::jsonb from products where slug = 'ceinture-aurion' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('vaultpop', 'VaultPop™ — Portefeuille Pop-Up RFID en cuir véritable', null, 'Ultra fin. Ultra pratique. Ultra sécurisé. Vous en avez assez des portefeuilles épais et désordonnés ? VaultPop™ combine un design moderne en aluminium, un accès instantané à vos cartes et une protection RFID pour garder vos données en sécurité au quotidien. ◈ Jusqu’à 15 cartes + billets ◈ Système pop‑up ◈ Protection RFID intégrée ◈ Design ultra fin', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'vaultpop-44438113124440', 'Brun Denime', null, 15900, 18500, 10, '["/assets/shopify/add26b4fcb.jpg"]'::jsonb from products where slug = 'vaultpop' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'vaultpop-44438113157208', 'Noire', null, 15900, 18500, 10, '["/assets/shopify/3b9739aa84.jpg"]'::jsonb from products where slug = 'vaultpop' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'vaultpop-44438113091672', 'Carbone', null, 15900, 18500, 10, '["/assets/shopify/f20d75d096.jpg"]'::jsonb from products where slug = 'vaultpop' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('cotonpur', 'Pack de 3 Boxers CotonPur™ : Le Confort Naturel au Quotidien', null, 'Redécouvrez le Vrai Confort avec le Boxer CotonPur Vous en avez assez des sous-vêtements qui irritent, retiennent la chaleur et se déforment ? Passez au niveau supérieur avec les boxers CotonPur™. Conçus avec un coton de première qualité, ils offrent une douceur inégalée, une respirabilité optimale et une durabilité exceptionnelle. ◈ 🌿 100% Coton Respirant ◈ 🛡️ Anti-Irritations & Hypoallergénique ◈ 💪 Durabilité Exceptionnelle ◈ ✨ Coupe Parfaite & Discrétion', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'cotonpur-44437537161304', 'L: 40 - 55 kg', null, 14500, 18000, 10, '[]'::jsonb from products where slug = 'cotonpur' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'cotonpur-44437537194072', 'XL: 55 - 65kg', null, 14500, 18000, 10, '[]'::jsonb from products where slug = 'cotonpur' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'cotonpur-44437537226840', '2XL: 65 - 80kg', null, 14500, 18000, 10, '[]'::jsonb from products where slug = 'cotonpur' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'cotonpur-44437537259608', '3XL: 80 - 90kg', null, 14500, 18000, 10, '[]'::jsonb from products where slug = 'cotonpur' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('arctic-vector', 'Arctic Vector™ - L''Élégante Sacoche au Design Professionnel', null, 'Élevez Votre Quotidien avec Style et Fonctionnalité Découvrez l''Arctic Vector™, bien plus qu''une simple sacoche : c''est le compagnon idéal de l''homme moderne, conçu pour allier élégance avant-gardiste et performance inégalée. ◈ Protection Contre les Intempéries ◈ Design Minimaliste, Impact Maximal ◈ Organisation Intuitive et Optimisée ◈ Légèreté et Durabilité', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'arctic-vector-43909587533912', 'Default Title', null, 19900, 32000, 10, '[]'::jsonb from products where slug = 'arctic-vector' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('born-pretty-kit', 'Born Pretty – Kit Polygel Professionnel pour Ongles avec Lampe UV/LED – Gel d''Extension 15 ml', null, 'Le kit pour ongles le plus complet pour faire ses ongles a la maison. Découvrez le Kit Polygel BORN PRETTY, une solution tout-en-un pour créer des ongles tendances, résistants et d’aspect professionnel à domicile ou en salon. Idéal pour les débutants comme pour les pro. ◈ Facile à utiliser – modèle le gel sans coulure ◈ Finition professionnelle – effet gel brillant ◈ Kit complet – tout ce dont vous avez besoin inclus ◈ Résultats longue tenue – jusqu’à plusieurs semaines', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'born-pretty-kit-43631257747544', 'Default Title', null, 14900, 19900, 10, '[]'::jsonb from products where slug = 'born-pretty-kit' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('silkflow', 'SilkFlow™ – Lot de 6 boxers homme ultra frais et respirant', null, '❄️ Dites adieu à la chaleur et à l’inconfort Le boxer SilkFlow™ vous offre une sensation de fraîcheur immédiate, même sous forte chaleur. ◈ Ultra léger ◈ Respirant ◈ Doux comme de la soie ◈ Invisible sous les vêtements', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'silkflow-43922741788760', '3XL (75 - 90 kg)', null, 19000, 24500, 10, '[]'::jsonb from products where slug = 'silkflow' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'silkflow-44128208846936', '4XL (90 - 120 kg)', null, 19000, 24500, 10, '[]'::jsonb from products where slug = 'silkflow' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;

insert into products (slug, name, category, description, active) values ('hbelt', 'H-Flex Belt™ – La ceinture sans boucle, confortable et ajustable', null, 'Découvrez la H-Flex Belt™, la ceinture révolutionnaire sans boucle qui vous offre confort et liberté totale. Fini la douleur au ventre, fini la boucle qui gêne : ◈ Confort absolu : fini la boucle qui rentre dans le ventre ◈ Ultra simple à utiliser : crochet + Velcro → prêt en 10 secondes ◈ Maintien parfait : votre pantalon reste en place toute la journée ◈ Unisexe & Taille Unique : s’adapte à toutes les morphologies', true) on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description;
insert into variants (product_id, sku, color, size, price, price_before, stock, images) select id, 'hbelt-44242930860120', 'Default Title', null, 11000, 13500, 10, '[]'::jsonb from products where slug = 'hbelt' on conflict (sku) do update set price = excluded.price, price_before = excluded.price_before;
